name: Production Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - name: SSH Clone or Pull
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd waripoke.xyz/public_html/

            # Gitリポジトリから最新のコードをクローンまたはプルする
            if [ ! -d ".git" ]; then
              git clone .
            else
              git pull
            fi

            # .env を作成
            cat << EOF > .env
            DJANGO_SETTINGS_MODULE=config.settings.config_prod
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            DATABASE_PORT=${{ secrets.DATABASE_PORT }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME_PROD }}
            DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME_PROD }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD_PROD }}
            GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
            EOF

            #仮想環境を作成
            pipenv --python 3

            # Pipfile.lock からパッケージをインストール
            pipenv sync

            # DB マイグレーション
            pipenv run python manage.py migrate

            # static ファイルの収集
            pipenv run python manage.py collectstatic --noinput

            # デプロイ設定のチェック
            pipenv run python manage.py check --deploy

            # index.cgi の作成とパーミッション変更
            cat << EOF > index.cgi
            #!$(pipenv --venv)/bin/python
            import sys

            import dotenv
            import pymysql

            # pipenvのパスを追加
            sys.path.insert(0, "$(pipenv --venv)/bin")

            # .envファイルから環境変数を読み込む
            dotenv.load_dotenv()

            # pymysql で MySQL を使えるようにする
            pymysql.install_as_MySQLdb()

            from wsgiref.handlers import CGIHandler
            from django.core.wsgi import get_wsgi_application

            # アプリケーションを起動
            application = get_wsgi_application()
            CGIHandler().run(application)
            EOF

            chmod 755 index.cgi
