# 本番環境へデプロイ
name: Production Deploy

on:
  # mainブランチへプッシュされたら動作
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      # FTP経由でファイルをサーバへ転送する
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: |
          exclude: |
            **/.**/**
            .editorconfig
            .gitignore

      # SSH経由でコマンドを実行する
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd waripoke.xyz/public_html/

            # .env を作成
            cat << EOF > .env
            DJANGO_SETTINGS_MODULE=config.settings.config_prod
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            DATABASE_HOST=${{ secrets.DATABASE_HOST }}
            DATABASE_PORT=${{ secrets.DATABASE_PORT }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
            DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
            GOOGLE_APPLICATION_CREDENTIALS=${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
            EOF

            # 仮想環境を作成
            python3 -m venv venv

            # 仮想環境を有効化
            source venv/bin/activate



            # DBマイグレーション
            python3 manage.py migrate

            # staticファイルの収集
            python3 manage.py collectstatic --noinput

            # デプロイ設定のチェック
            python3 manage.py check --deploy

            # index.cgi を作成
            cat << EOF > index.cgi
            #!$(pwd)/venv/bin/python
            import sys, os

            !source venv/bin/activate

            sys.path.insert(0, "$(pwd)")

            os.environ['DJANGO_SETTINGS_MODULE'] = 'app_config.settings'

            from wsgiref.handlers import CGIHandler
            from django.core.wsgi import get_wsgi_application

            application = get_wsgi_application()
            CGIHandler().run(application)
            EOF

            # index.cgi のパーミッションを変更
            chmod 755 index.cgi








